version: '3'
services:
  nextclouddev:
    build: .
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/var/www/html
      - ../../customapps:/var/www/html/customapps
      - ../../data:/var/www/html/data
      - ../../config:/var/www/html/config
    command: /var/www/html/.devcontainer/entrypoint.sh
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
        
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ../../data/db:/data/postgres
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025


